(function(){var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},n=ca(this),p=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}},r=function(a){return q(a,a)},q=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},u=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+
" is not an iterable or ArrayLike");},da=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b},v;if(typeof Object.setPrototypeOf=="function")v=Object.setPrototypeOf;else{var w;a:{var ea={a:!0},x={};try{x.__proto__=ea;w=x.a;break a}catch(a){}w=!1}v=w?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var y=v,z=function(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(y)y(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.ma=b.prototype},fa=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};
p("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.i=function(d){if(this.g==null){this.g=[];var f=this;this.j(function(){f.o()})}this.g.push(d)};var e=n.setTimeout;b.prototype.j=function(d){e(d,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(k){this.l(k)}}}this.g=null};b.prototype.l=function(d){this.j(function(){throw d;
})};var g=function(d){this.i=0;this.j=void 0;this.g=[];this.H=!1;var f=this.l();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.l=function(){function d(k){return function(l){h||(h=!0,k.call(f,l))}}var f=this,h=!1;return{resolve:d(this.V),reject:d(this.o)}};g.prototype.V=function(d){if(d===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.ha(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=
!1}f?this.U(d):this.v(d)}};g.prototype.U=function(d){var f=void 0;try{f=d.then}catch(h){this.o(h);return}typeof f=="function"?this.ka(f,d):this.v(d)};g.prototype.o=function(d){this.N(2,d)};g.prototype.v=function(d){this.N(1,d)};g.prototype.N=function(d,f){if(this.i!=0)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.i);this.i=d;this.j=f;this.i===2&&this.W();this.O()};g.prototype.W=function(){var d=this;e(function(){if(d.T()){var f=n.console;typeof f!=="undefined"&&
f.error(d.j)}},1)};g.prototype.T=function(){if(this.H)return!1;var d=n.CustomEvent,f=n.Event,h=n.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=n.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return h(d)};g.prototype.O=function(){if(this.g!=null){for(var d=0;d<this.g.length;++d)D.i(this.g[d]);
this.g=null}};var D=new b;g.prototype.ha=function(d){var f=this.l();d.s(f.resolve,f.reject)};g.prototype.ka=function(d,f){var h=this.l();try{d.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};g.prototype.then=function(d,f){function h(m,t){return typeof m=="function"?function(E){try{k(m(E))}catch(F){l(F)}}:t}var k,l,G=new g(function(m,t){k=m;l=t});this.s(h(d,k),h(f,l));return G};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.s=function(d,f){function h(){switch(k.i){case 1:d(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;this.g==null?D.i(h):this.g.push(h);this.H=!0};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var k=u(d),l=k.next();!l.done;l=k.next())c(l.value).s(f,h)})};g.all=function(d){var f=u(d),h=f.next();return h.done?c([]):new g(function(k,l){function G(E){return function(F){m[E]=F;t--;t==0&&k(m)}}var m=[],t=0;do m.push(void 0),t++,c(h.value).s(G(m.length-
1),l),h=f.next();while(!h.done)})};return g});p("globalThis",function(a){return a||n});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=function(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.na=function(e,g,D){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[g].apply(e,d)}};var B=function(a){this.g=a};function C(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,C);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}A(C,Error);C.prototype.name="CustomError";function H(a,b){a=a.split("%s");for(var c="",e=a.length-1,g=0;g<e;g++)c+=a[g]+(g<b.length?b[g]:"%s");C.call(this,c+a[e])}A(H,C);H.prototype.name="AssertionError";var I=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var g=Array.prototype.slice.call(arguments,2)}throw new H(""+e,g||[]);}};var ha="closure_listenable_"+(Math.random()*1E6|0);var J=function(a){this.g=a};z(J,B);J.prototype[ha]=!0;var K=function(a){this.g=a};z(K,J);var L=function(a,b){this.g=a;this.i=b||null};z(L,B);L.prototype.then=function(a,b,c){var e;a&&(e=ia(this,a));this.g.aa(e,b,c)};var ia=function(a,b){var c=a.i;return c?function(e){b.call(this,new c(e))}:b};var ja=[];var M=function(a){this.g=a||gbar.a;this.j=this.i=null};z(M,B);var ka=function(){var a=N();a.i||(a.i=new L(a.g.bf(),K));return a.i},la=function(){var a=N();a.j||(a.j=new L(a.g.bh()));return a.j},N=function(){I(!Object.isSealed(M),"Cannot use getInstance() with a sealed constructor.");var a="u";if(M.u&&M.hasOwnProperty(a))a=M.u;else{ja.push(M);var b=new M;M.u=b;I(M.hasOwnProperty(a),"Could not instantiate singleton.");a=b}return a};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var O={};function P(){if(O!==O)throw Error("Bad secret");};var Q=globalThis.trustedTypes,R;function ma(){var a=null;if(!Q)return a;try{var b=function(c){return c};a=Q.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){throw c;}return a};var S=function(a){P();this.g=a};S.prototype.toString=function(){return this.g+""};function na(a){R===void 0&&(R=ma());var b=R;return new S(b?b.createScriptURL(a):a)};var oa=r([""]),pa=q(["\x00"],["\\0"]),qa=q(["\n"],["\\n"]),ra=q(["\x00"],["\\u0000"]),sa=r([""]),ta=q(["\x00"],["\\0"]),ua=q(["\n"],["\\n"]),va=q(["\x00"],["\\u0000"]);function T(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function U(a){return a.toString().indexOf("`")===-1}var wa=U(function(a){return a(oa)})||U(function(a){return a(pa)})||U(function(a){return a(qa)})||U(function(a){return a(ra)}),xa=T(sa)&&T(ta)&&T(ua)&&T(va);var V=function(a){P();this.g=a};V.prototype.toString=function(){return this.g};new V("about:blank");new V("about:invalid#zClosurez");var ya=[],za=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};ya.indexOf(za)===-1&&ya.push(za);function Aa(a){var b=fa.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!wa&&a===a.raw||!(wa&&!xa||T(a))||b.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(b.length===0)return na(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var e=c.indexOf("//")+2;var g=c.indexOf("/",e);if(g<=e)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");e=c.substring(e,g);if(!/^[0-9a-z.:-]+$/i.test(e))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(e))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(e))throw Error("The top-level domain must start with a letter.");e=!0}else e=!1;if(!e)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")e=!0;else throw Error("The path start in the url is invalid.");else e=!1;if(!(e=e||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");e=!0}else e=!1;if(!e)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return na(c)};var Ba=r(["https://accounts.google.com/gsi/client"]),Ca=r(["https://apis.google.com/js/client.js"]);function W(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");Da?(Ea=!0,Fa&&X()):X()}
var X,Y=null,Z=window,Ga=Z.colabExperiments&&Z.colabExperiments.gis_auth,Ha=Z.colabExperiments&&Z.colabExperiments.first_party_auth,Ia=Z.colabExperiments&&Z.colabExperiments.rt,Da=Ga&&(!Ha||Ia),Fa=!1,Ea=!1,Ja=document.getElementsByTagName("script")[0],Ka=Aa(Ba);
function La(){if(Y)return Y;window.performance.mark("gapi_load_start");return Y=new Promise(function(a,b){X=a;Da&&Ma(function(){b(Error("Error loading "+Ka))});if(Ha&&typeof gbar!=="undefined")la().then(function(){Ga?gapi.load("client",W):gapi.load("auth:client",W)}),ka().then(function(e){var g=document.documentElement.getAttribute("theme")==="dark";g&&(e.g.pp(g),e.g.pd("transparent"))});else{Z.gapi_onload=W;var c=Aa(Ca);Na({src:c,onerror:function(){b(Error("Error loading "+c))}})}})}
function Ma(a){Na({src:Ka,onload:function(){Fa=!0;Ea&&X()},onerror:a})}
function Na(a){var b=document;var c="SCRIPT";b.contentType==="application/xhtml+xml"&&(c=c.toLowerCase());c=b.createElement(c);b=a.src;if(b instanceof S)b=b.g;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");c.src=b;var e;b=c.ownerDocument&&c.ownerDocument.defaultView||window;b=b===void 0?document:b;var g;b=(g=(e="document"in b?b.document:b).querySelector)==null?void 0:g.call(e,"script[nonce]");(e=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&c.setAttribute("nonce",e);c.async=
!0;a.onload&&(c.onload=a.onload);a.onerror&&(c.onerror=a.onerror);Ja.parentNode.insertBefore(c,Ja)}Z.colab_gapi_loader={load:La};La().then(function(){},function(){});}).call(this);
